### ISSUE TITLE
APIC can't visible on itunes if description is empty.

### ISSUE THREAD

**Issue by jin60641** [Zazama/node-id3#101]
If data.description is undefined,

(current version, encoding 0x01, iTunes can't parse APIC)
<img width="395" alt="스크린샷 2021-01-01 오후 4 16 53" src="https://user-images.githubusercontent.com/9072743/103435049-db92f980-4c4c-11eb-888a-4eb32c88f080.png">

(~v1.0.19, encoding 0x00, so test will failed, but iTunes can parse APIC)

<img width="390" alt="스크린샷 2021-01-01 오후 4 16 43" src="https://user-images.githubusercontent.com/9072743/103435048-d9c93600-4c4c-11eb-9d53-4a02442c861d.png">
<img width="275" alt="스크린샷 2021-01-01 오후 4 19 23" src="https://user-images.githubusercontent.com/9072743/103435066-1eed6800-4c4d-11eb-8cf5-726ff4d90a82.png">

result of APIC buffer. current and v1.0.19
<img width="1297" alt="스크린샷 2021-01-01 오후 3 57 00" src="https://user-images.githubusercontent.com/9072743/103435050-db92f980-4c4c-11eb-8149-4aaac4fef259.png">

It is a iTunes bug? or node-id3's bug? anyway, how about handle empty description?

**Comment by Zazama** [comment]
This seems to be a bug in iTunes actually. Changing the number 0x01 to 0x00 changes the encoding from UTF-16 (0x01) to ISO-8859-1 (0x00).

By definition of the picture tag:

```
<Header for 'Attached picture', ID: "APIC">
Text encoding   $xx
MIME type       <text string> $00
Picture type    $xx
Description     <text string according to encoding> $00 (00)
Picture data    <binary data>
```

You can see that description is terminated by one "0x00" if using ISO-8859-1 encoding, but by "0x0000" if using UTF-16 encoding. This is because UTF-16 uses two bytes per character.
So, according to specs, everything is correct here.

The best fix is probably to use encoding 0x00 if the description is empty (As I just saw, you pushed a pull request doing that, thanks! :) )
I will adjust the tests and push a new version today.

**Comment by jin60641** [comment]
@Zazama Yes, I think handling empty description is a best way :)

**Comment by jin60641** [comment]
on v0.2.2, iTunes can't parse APIC after calling `NodeID3.update` without any APIC params.
I didn't pass any exclude or include options.
why?
