### ISSUE TITLE
Rename the TP2/TPE2 alias to "albumArtist"

### ISSUE THREAD

**Issue by HermanLederer** [Zazama/node-id3#108]
Currently the alias for TP2 in v2.2 and TPE2 in v2.3 is "performerInfo", but popular software and services like Amazon music, Groove Music (the default Windows 10 player), [MP3TAG](https://www.mp3tag.de/en/index.html) (a popular tag editing software), [Retro Music](https://github.com/h4h13/RetroMusicPlayer) (a player app with over a million downloads on playstore) and Samsung Music (the default player on Samsung phones) call it the "album artist".

I am making my own tag editing app inspired by MP3TAG and it was very confusing when I was unable to find the album artist property. I actually started editing the package just to realize that TPE2 frame is already included, just not aliased like I expected.

I think it is going to be more clear for developers if the alias is renamed to "albumArtist"

**Comment by Zazama** [comment]
I think originally I named it performerInfo because the specs state

> TPE2
> The 'Band/Orchestra/Accompaniment' frame is used for **additional information about the performers** in the recording. 

I get your point, though. What's problematic about changing the default alias is that projects are already using the "performerInfo" key and I don't think breaking that functionality in a normal version bump would be a good idea.

Do you think it would help to write a note into the README.md file next to performerInfo saying that it's used for the album artist?

**Comment by HermanLederer** [comment]
That sounds like a good solution. I was referring to the README.md at first so at least in my case it would have prevented the confusion

**Comment by Zazama** [comment]
Now included in the README
https://github.com/Zazama/node-id3/releases/tag/0.2.3
