### ISSUE TITLE
Add constants for obscure tag values

### ISSUE THREAD

**Issue by Zazama** [Zazama/node-id3#123]
As discussed in https://github.com/Zazama/node-id3/pull/122, values like `synchronisedLyrics.timeStampFormat` require obscure values, in this example 0x01 or 0x02, for the tag to be valid. Normal users shouldn't have to read the specs and their code should be readable. If you write

```
synchronisedLyrics: { timeStampFormat: 0x01 }
```
you will probably not know the meaning after some time.
Instead, introduce constants like:

```
synchronisedLyrics: { timeStampFormat: TimeStampFormat.MILLISECONDS }
```

As @pbricout suggested, the `TagConstants` namespace should be appropriate.

To do:
1. Check the specs for all important constants
2. Create the constants in the library
3. Refactor documentation & some existing code like APIC definitions

**Comment by pbricout** [comment]
About point 3, I did notice the current particular case for APIC tag frame, here are some comments about it.

The documentation uses the terminology `picture` but the current implementation uses [`image`](https://github.com/Zazama/node-id3/blob/fa12a30bf21cab4e42deb1fb1343c852acc69f32/src/ID3Definitions.js#L87) as the property name.

The documentation uses the term `pictureType` but the library currently uses `type` as the property name
It would have been nicer to align terminology with the documentation as much as possible.

Also to better align with the rest of the library `pictureType` should just have been a number in both `create` and `read`. To better separate concerns, the name could be retrieve separately from the the type. More on this below.

Fixing these now would introduce breaking changes, so I suppose we will leave with it that way.  Later we could introduced a new major version with breaking changes.

Some issues the way this is currently implemented:

- the create and read API are asymmetric:
  The picture type is currently hard-coded to 3 (Front Cover) [here ](https://github.com/Zazama/node-id3/blob/fa12a30bf21cab4e42deb1fb1343c852acc69f32/src/ID3Frames.js#L77), but is returned as an object with properties `type: { id: number, name: string }`.\
  I am not sure why the name is returned here, usually a name is used either to display in a UI or as a debug facility. Also names are usually preferred to numbers (easier to work with), but here since we are very close to the format for all the other frames (all the other frames accept and return numbers), I think we should have returned just `type: number`.

Ideally for APIC we would like to have the `read` return an object format compatible with the `create`, imagine, you read all the tags and want to rewrite them (which I will need to do in my code), then you can `read` => `modify/delete/add` => `write` (note that `update` unfortunately has a particular case for tags with multiple values, I won't extend on that here).

With that in mind, I suggest the following changes:

- provide a set of constant definitions for the picture type
- for `create` 
  - accepts `type` as an object `{ id: number }` (`name` should be ignored), accepting the object format allow to make it compatible with the value returned by `read`, we could also potentially accept `type` as a number, but that would complicate code for both the library and clients of the library, I leave this open for discussion
- for `read`
  - nothing to change I believe
- update the documentation to specify that `name` is an informational only provided by `read` but not accepted by `create`

**Comment by pbricout** [comment]
I will try to provide a PR for this after this one <https://github.com/Zazama/node-id3/pull/124>.

**Comment by Zazama** [comment]
Hi @pbricout,

you're absolutely correct about the APIC frame, especially the hardcoded cover type. To give some context about the naming choices, the first implementation was commited 6 years ago (https://github.com/Zazama/node-id3/commit/1d0a550af9e1381751df1d303d1e37340d462e07) and it was honestly a mess itself 😄 I didn't really think much about naming choices etc., just wanted it to work back then. But with more inconsistencies, it's clear that it was a bad choice. I also don't remember why I chose to add the name to the type.

However, I've always tried not to break anything when re-writing things while the library is at version 0.x, which is why I don't think renaming is an option for now, like you said. I wanted to at least get all v2.3.0 frames working before upping to 1.x. I'd probably wait with accepting `type` as a number until the read implementation can be changed. The hardcoded type is definitely a bug, though.

**Comment by pbricout** [comment]
What do you think if we simply use `Constants` instead of `TagConstants` ? Since this is in the context of a tag library, maybe the tag prefix isn't necessary?

**Comment by Zazama** [comment]
Merged in https://github.com/Zazama/node-id3/commit/17a247909a6cf3c2ebe051f3ebadf61ab3b7ab4f / https://github.com/Zazama/node-id3/commit/ed4495bfdfaca43e78151be239181a6e69fd007d, thanks!
