### ISSUE TITLE
Updating tags in AIFF files makes tags/audio unreadable by other applications

### ISSUE THREAD

**Issue by darrendavid** [Zazama/node-id3#145]
I've been working on a custom tagging solution for my tracks, and the latest version is great at recognizing the new tags. I am unable, however, to successfully add/update tags in AIFF files. 

If I update any tag, I can do NodeID3.read() and confirm that the tag was successfully added to the ID3 block in the AIFF file. However, when I attempt to access those tags from a third-party application (on Windows, I've tried Tag & Rename and Rekordbox DJ software), once I refresh the database to check the new tags, ALL tags are unavailable. When I attempt to open the updated AIFF file in Adobe Audition, I get the following error:

`Error: This file is not supported by libsndfile. Code: 32. Channel count is zero.`

This behavior doesn't happen with MP3 files.

Sample code and affected files [available for download here](https://drive.google.com/file/d/1-qmJwrKmjwde8J_qG9PR2dgv6sRemqCn/view?usp=sharing).

**Comment by pbricout** [comment]
This library is not designed to work with AIFF file format directly.
ID3 Tag is primarily designed to be transparent for MPEG streamed audio file format.
AIFF case is special. AIFF file format, it is a different file format and based on chunks.
An ID3 library can read from AIFF because it can find the ID3 block anywhere in the file.
However in the case of the AIFF file format, updating/writing/rewriting is not possible directly with this library as any change will move the ID3 block to beginning, this breaks the AIFF file format.
The correct way to do it is to use an AIFF library, to read the AIFF ID3 chunk to process with this library and to give it back to the AIFF library to rewrite/update the ID3 chunk.
See
https://exiftool.org/TagNames/AIFF.html
and
https://exiftool.org/TagNames/ID3.html

See also:
https://en.wikipedia.org/wiki/Audio_Interchange_File_Format

**Comment by Zazama** [comment]
Yes, this is not working and is out of scope for this library atm.
You will have to use an AIF parser and replace the ID3 tag or replace the buffer and chunk size manually.

Something like this: https://gist.github.com/Zazama/9e83dee3ca074f3ff907d8d034b77efb (be careful with that code, there are no validity checks)

**Comment by Zazama** [comment]
Feel free to write if you have questions, I'm just closing because this is something that this library is not handling

**Comment by adidahiya** [comment]
Heads up to others who attempted to use this library to write tags to AIFF files like myself and may have corrupted some of their media files. I found that [node-taglib-sharp](https://github.com/benrr101/node-taglib-sharp) works perfectly fine for AIFF files :+1:
