### ISSUE TITLE
Support for audio formats other than mp3

### ISSUE THREAD

**Issue by Sandakan** [Zazama/node-id3#154]
Can I know whether node-id3 will support reading and writing tags to audio formats like
- flac
- ogg
- wav

**Comment by Zazama** [comment]
This library is for ID3 tags only, that means it can't be used for flac and ogg because both use Vorbis Comments (which is like ID3 a tagging format but completely different).

WAV and AIFF could in theory be supported but our focus is to completely implement the ID3 spec for now (see https://github.com/Zazama/node-id3/issues/145). You can actually read ID3 tags from wav/aiff files using node-id3, but not write them.

You can check out this project for writing flac/ogg support https://github.com/ishowshao/metaflac-js, if you only need to read the tags, I often recommend https://www.npmjs.com/package/music-metadata as alternative

**Comment by Zazama** [comment]
I'm going to close this to keep the issues cleaned up but you can comment further if there's more you want to discuss 🙂

**Comment by Sandakan** [comment]
> This library is for ID3 tags only, that means it can't be used for flac and ogg because both use Vorbis Comments (which is like ID3 a tagging format but completely different).
> 
> WAV and AIFF could in theory be supported but our focus is to completely implement the ID3 spec for now (see #145). You can actually read ID3 tags from wav/aiff files using node-id3, but not write them.
> 
> You can check out this project for writing flac/ogg support https://github.com/ishowshao/metaflac-js, if you only need to read the tags, I often recommend https://www.npmjs.com/package/music-metadata as alternative

I was actually using both music-metadata and node-id3
music-metadata for reading tags cause it provides support for a lot of audio formats.
node-id3 for writing tags.

**Comment by adidahiya** [comment]
[node-taglib-sharp](https://github.com/benrr101/node-taglib-sharp) works pretty well
