### ISSUE TITLE
Cant find mp3 files from outside __dirname?

### ISSUE THREAD

**Issue by ReallyComeOn** [Zazama/node-id3#16]
If I put the mp3's in a music folder in the project directory and do 

var read = nodeID3.read('./music/song.mp3)
It works perfectly but lets say I put them in the music folder in the linux home directory and do 

var read = nodeID3.read('~/Music/song.mp3)
It doesn't work.. 
I've also tried other paths like '/home/USER/Music/song.mp3 and etc, any idea on how to fix?

**Comment by Zazama** [comment]
First off, I think you're missing a closing apostrophe.

`var read = nodeID3.read('~/Music/song.mp3)`
should be
`var read = nodeID3.read('~/Music/song.mp3')`

If that's not the problem, are you sure the path is correct? Because it is just forwarded to node.js's standard filesystem library:

`filebuffer = fs.readFileSync('~/Music/song.mp3');`
