### ISSUE TITLE
Add support for the TXXX frame (user defind text information)

### ISSUE THREAD

**Issue by cxcorp** [Zazama/node-id3#18]
Some music players such as foobar2000 can store metadata in the TXXX frame. The frame might contain statistics such as the timestamps for when the track was first played, etc. There may be multiple TXXX frames in a file, but the descriptions are unique.

The frame body is arranged a bit differently from ordinary text frames, [like so](http://id3.org/id3v2.3.0#User_defined_text_information_frame):

```
<Header for 'User defined text information frame', ID: "TXXX">
Text encoding    $xx
Description    <text string according to encoding> $00 (00)
Value    <text string according to encoding>
```

Here's an example of the TXXX frame in a file:

```
00000000  49 44 33 03 00 00 00 06  6b 15 54 49 54 32 00 00  |ID3.....k.TIT2..|
00000010  00 25 00 00 01 ff fe 44  00 65 00 6d 00 6f 00 6c  |.%.....D.e.m.o.l|
00000020  00 69 00 74 00 69 00 6f  00 6e 00 20 00 53 00 71  |.i.t.i.o.n. .S.q|
00000030  00 75 00 61 00 64 00 00  00 54 50 45 31 00 00 00  |.u.a.d...TPE1...|
00000040  1b 00 00 01 ff fe 48 00  61 00 72 00 72 00 79 00  |......H.a.r.r.y.|
00000050  20 00 4a 00 75 00 64 00  64 00 61 00 00 00 54 58  | .J.u.d.d.a...TX| <--
00000060  58 58 00 00 00 39 00 00  01 ff fe 41 00 44 00 44  |XX...9.....A.D.D|
00000070  00 45 00 44 00 00 00 ff  fe 32 00 30 00 31 00 37  |.E.D.....2.0.1.7|
00000080  00 2d 00 30 00 37 00 2d  00 32 00 39 00 20 00 31  |.-.0.7.-.2.9. .1|
00000090  00 36 00 3a 00 32 00 31  00 3a 00 30 00 30 00 00  |.6.:.2.1.:.0.0..|
000000a0  00 54 43 4f 4e 00 00 00  0d 00 00 01 ff fe 48 00  |.TCON.........H.|
000000b0  6f 00 75 00 73 00 65 00  41 50 49 43 00 01 ac 75  |o.u.s.e.APIC...u|
```

**Comment by kbuffington** [comment]
This would be super useful to me as well.

**Comment by kbuffington** [comment]
@Zazama I've been working on this for the last few days, and my fork now has support for reading TXXX frames, and also true handling of multi-value frames (instead of just concatentation). I expect to have the write portion for TXXX and multi-value done in the next day or two. I'm also considering bumping the write to v2.4. Anyway, in the process of this work and without thinking too much about it, I converted the entire project to Typescript and used the linting rules I'm used to, so even though the actual code is almost identical it's morphed into a radically different project. I can submit a PR if you like, but I have a feeling you wouldn't want to approve.

How should I handle this? Would you prefer I create my own true fork with a different name? I could leave it as just a regular fork of this project, but discoverability would suffer and there's not an easy way to `npm install` it. I don't want you to step on your toes, but my guess is others could benefit from the work I've done as well.

**Comment by Zazama** [comment]
Hey @kbuffington, I completely agree with you that others could and **should** benefit from the work you've done here. Of course the situation is kinda problematic, because I don't think converting the project to typescript is an option for me right now. In addition to that, you may have noticed that node-id3's development is _kinda_ slow from my side. I feel like there are three options:

1. Me/You porting your changes to this project, but (for me) right now I don't know when.
2. You letting it stay a fork which, like you said, is problematic.
3. You creating a whole new package. It's not like I'd be mad, I'd even post a note into my README.md for users searching an alternative. Yet, I see another problem with this solution, which is fragmentation. I think two growing slightly different libraries won't be as good as a single one with different contributions.

But in the end, I'll leave the decision to you. I think your work should be recognized, so decide what you think is best.

**Comment by TheBrenny** [comment]
Bump. 🤷‍♂️ I would absolutely love the ability to put some minified JSON in the ID3 tag, but I haven't got the time to flick through the code.

**Comment by Zazama** [comment]
https://github.com/Zazama/node-id3/commit/ad719c1b6c61034660740beb1a08e32f60f08647 Would you mind trying the new index.js from the repository?

Usage:

```javascript
TXXX: [{
  description: "txxx name",
  value: "TXXX value text"
}, {
  description: "txxx name2",
  value: "TXXX value text 2"
}]
```
