### ISSUE TITLE
Write ID3 tags to flac?

### ISSUE THREAD

**Issue by J05HI** [Zazama/node-id3#28]
Hello,

how to write ID3 tags to flac files with this lib?

Thanks!

**Comment by Fantasy9527** [comment]
I want to do that too

**Comment by Zazama** [comment]
I understand your request but unfortunately, this library isn't suited for flac files.
While you may just write the id3-tags to your flac files like with mp3s, this will cause compatibility problems with players because flac uses a different tagging-system called vorbis comments. Therefore, you should search for a vorbis comments library.

**Comment by J05HI** [comment]
Okay thanks :)
