### ISSUE TITLE
m4a/aac file support

### ISSUE THREAD

**Issue by TrueTiem** [Zazama/node-id3#50]
Probably you're not developing this anymore but in my opinion this is the best node id3 parser/writer. Whatever, I noticed that when i try to write id3 tags to a m4a file, it breaks the file and doesn't write tags.
I converted one of the m4a files to mp3 with ffmpeg and run with same code and it worked.
I guess the problem is with m4a files. Can you add support for aac/m4a please?

**Comment by Zazama** [comment]
Hi,

is there a specific reason you want to use ID3 tags in m4a files? Because mp4 file formats usually use their own tagging format, take a look here: https://www.npmjs.com/package/mp4edit

For aac files, I don't know if there is a working node.js implementation, but you can try to use mp4edit, because I think they share the same tagging format. If not, try the nodejs TagLib implementation.

**Comment by TrueTiem** [comment]
No, there are many audio files including mp3, m4a and few ogg. For now i separated them and use 3rd party app for m4a. But i'm gonna try these. Thank you.

**Comment by subhog** [comment]
I'm not sure about mp4edit, but I just needed the same thing and found a great tool that works:
https://github.com/nathanpeck/exiftool

**Comment by TrueTiem** [comment]
I guess it does not write metadata, only parses. I'm using tageditor for now, if anyone needs. Supports both cli and gui. https://github.com/Martchus/tageditor
